version: '3'
services:
  app:
    container_name: projectserver2
    restart: always
    build: .
    ports:
      - '82:82'
    depends_on:
      - 'mongo'
  mongo:
    container_name: mongo_projectserver2
    restart: always
    image: mongo
    ports: 
     - '27017:27017'
    volumes:
     - db-data:/data/db
     - mongo-config:/data/configdb

volumes:
  db-data: 
  mongo-config: